version: '3'
services:
  solr:
    image: solr:8.4.1
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - ./conf:/opt/solr/server/solr/configsets/edismax-json-queries/conf
    command:
      - /bin/sh
      - -c
      - |
        solr-precreate techproducts /opt/solr/server/solr/configsets/edismax-json-queries
        post -c techproducts example/exampledocs/manufacturers.xml
volumes:
  data:
  conf:
